name: Lint & Test

on:
  push:
    branches-ignore:
      - main

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: psf/black@stable

  flake8-py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: x64
      - uses: actions/checkout@v4
      - run: pip install flake8
      - uses: suo/flake8-github-action@releases/v1
        with:
          checkName: "flake8-py3" # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}